spring:
  application:
    name: chartered_bus
  datasource:
    url: jdbc:oracle:thin:@your_rds_endpoint:1521:your_db_name
    username: your_db_username
    password: your_db_password
    driver-class-name: oracle.jdbc.OracleDriver